mpesa/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import  get_access_token, lipa_na_mpesa_online, register_urls, call_back, validation, confirmation, lipa_na_mpesa

app_name = "mpesa"

urlpatterns = [
    path("lipa_na_mpesa/<int:plot_no>/<int:amount>/", lipa_na_mpesa, name="lipa-mpesa"),

    # mpesa
    path("get_access_token/", get_access_token, name="mpesa-access-token"),
    path("lipa_online/", lipa_na_mpesa_online, name="mpesa-online"),

    # c2b
    path("c2b/register/", register_urls, name="register-urls"),
    path("c2b/validation/", validation, name="validation"),
    path("c2b/confirmation/", confirmation, name="condfirmation"),
    path("c2b/callback/", call_back, name="callbacks")
]

property/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import map_view, dashboard_view, land_parcels, landing_page, graph_data, ussd_callback, send_message

app_name = "property"

urlpatterns = [
    path("", landing_page, name="landing"),
    path("map/", map_view, name="map"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("parcels/", land_parcels, name="land-parcels"),
    path("graph_data/", graph_data, name="graph-data"),
    path("ussd_callback/",ussd_callback, name="ussd-callback"),
    path("send_message/", send_message, name="send-message")
]

# configure static anf media files
if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property_taxation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
    path("api/", include("mpesa.urls")),
    path("", include("property.urls")),
   
]

user/urls.py
from django.urls import path

# authentication
from django.contrib.auth.views import LoginView, LogoutView
from .views import ProfileView, UserCreateView, ProfileCreateView


# application namspace
app_name = "user"

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="user/login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="user/logout.html"), name="logout"),

    path("create_profile/", ProfileCreateView.as_view(), name="create-profile"),
    path("account/", ProfileView.as_view(), name="profile")
]   

property/models.py
from django.contrib.gis.db import models

class Parcels(models.Model):
    id = models.BigIntegerField()
    geom = models.MultiPolygonField(srid=3857, blank=True, null=True)
    plot_no = models.BigIntegerField(primary_key=True)
    owner = models.CharField(max_length=50, blank=True, null=True),
    zone = models.CharField("Parcel Zone", max_length=50, default="Zone A")

    class Meta:
        managed = False
        db_table = 'parcels'

class TaxationHistory(models.Model):
    PAYMENT_MODE = (
        ('MPESA', "M-PESA"),
        ('Bank', "Bank")
    )

    # parcel = models.ForeignKey(Parcels, db_column='plot_no', on_delete=models.CASCADE)
    plot_no = models.BigIntegerField(blank=True, null=True)
    payed_on = models.DateTimeField("Payed On", auto_now=False, auto_now_add=False)
    is_waived = models.BooleanField("Waiver", default=False)
    payment_mode = models.CharField("Payment Method", max_length=50, choices=PAYMENT_MODE)
    amount = models.IntegerField("Amount", blank=True, null=True)
    balance = models.IntegerField("Arrear", default=0)
    transaction_id = models.CharField("Transaction Id", max_length=50)
    id_number = models.IntegerField("Id Number")

    class Meta:
        verbose_name = "Tax History"
        verbose_name_plural = "Tax History"

    def __str__(self):
        return self.transaction_id

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

class ParcelInfo(models.Model):
    id = models.IntegerField(primary_key=True)
    parcel = models.OneToOneField(Parcels, db_column='plot_no', blank=True, null=True, on_delete=models.CASCADE)
    owner = models.CharField(max_length=255, blank=True, null=True)
    arrears = models.CharField(max_length=100, blank=True, null=True)
    is_cleared = models.BooleanField("Arrears Cleared", default=False)
    id_number = models.BigIntegerField("Owner Id Number", unique=False)
    phone_number = models.CharField("Phone Number", max_length=15, blank=True)

    class Meta:
        managed = False
        db_table = 'parcel_info'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from PIL import Image

class User(AbstractUser):
    username = models.CharField("Username", max_length=50, unique=True)
    email = models.EmailField("Email", max_length=254)
    first_name = models.CharField("First Name", max_length=50)
    last_name = models.CharField("Last Name", max_length=50)
    surname = models.CharField("Surname", max_length=50)
    id_number = models.BigIntegerField("Id Number", unique=True)
    is_taxpayer = models.BooleanField("Tax Payer", default=False)


    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['id_number', 'email']

    def __str__(self):
        return self.username
    
    def get_full_name(self):
        return self.first_name +" " + self.last_name + " " + self.surname
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField("Profile Picture", upload_to="profile_picture", default="user.png")
    phone_number = models.CharField("Phone Number", max_length=13, null=True)

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.image.path)

        if image.height > 300 or image.width > 300:
            output_size = (300, 300)
            image.thumbnail(output_size)
            image.save(self.image.path)


    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User, UserProfile

class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'id_number', 'password1', 'password2']
    
class UserDetailsForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ['username', 'password1', 'password2']

class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", max_length=50, required=False)
    last_name = forms.CharField(label="Last Name", max_length=50, required=False)
    surname = forms.CharField(label="Surname", max_length=50, required=False)
    email = forms.EmailField(label="Email", required=False)
    phone_number = forms.CharField(
        label="Phone Number", max_length=13, required=False,
        help_text="Phone Number format: 254700111222",
        widget=forms.TextInput(attrs={
            'placeholder':'254700111222',
            'pattern':r'254[0-9]{9}'
        })
    )
    
    class Meta:
        model = UserProfile
        fields = ['image', 'phone_number']

property/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum, Q
from django.views.decorators.csrf import csrf_exempt

# serializer
from django.core.serializers import serialize

# models
from .models import ParcelInfo, Parcels, TaxationHistory

# utils
import json
import requests
from datetime import datetime

def landing_page(request):
    if request.GET.get('plot_no'):
        plot_no = request.GET.get('plot_no')
        try:
            parcel = ParcelInfo.objects.get(parcel = plot_no)
            parcel = {'arrears':parcel.arrears, 'parcel':parcel.parcel}
        except ParcelInfo.DoesNotExist:
            parcel = "None"
        
        context = {'parcel':parcel}
    else:
        context =  {}
        
    return render(request, 'property/landing.html', context)

def graph_data(request):
    arrears_zone = ParcelInfo.objects.values('parcel__zone').annotate(total=Sum('arrears'))
    collection_history = TaxationHistory.objects.values('payed_on__year').annotate(total=Sum('amount'))
    payment_mode = TaxationHistory.objects.values('payment_mode').annotate(total=Sum('amount'))

    arrears_zone = [{ar['parcel__zone']:ar['total']} for ar in arrears_zone]
    collection_history = [{ar['payed_on__year']:ar['total']} for ar in collection_history]
    payment_mode = [{ar['payment_mode']:ar['total']} for ar in payment_mode ]

    return JsonResponse({'arrear':arrears_zone, 'collection':collection_history, 'payment_mode':payment_mode})

    # 
# Create your views here.
def map_view(request):
    return render(request, 'property/map.html')

def dashboard_view(request):
    context = {}
    context['parcels_count'] = Parcels.objects.all().count()
    context['owner_count'] = ParcelInfo.objects.values('id_number').annotate(Count('id_number', distinct=True)).count()
    context['arrears'] = ParcelInfo.objects.aggregate(total = Sum('arrears'))

    # collected this year
    currentTime = datetime.now()
    year = currentTime.year
    dt = datetime(year, 1, 1)
    context['collected'] = TaxationHistory.objects.filter(payed_on__gte = dt).aggregate(total=Sum('amount'))
    context['arrears_zone'] = ParcelInfo.objects.values('parcel__zone').annotate(total=Sum('arrears'))
    context['collection_history'] = TaxationHistory.objects.values('payed_on__year').annotate(total=Sum('amount'))
    context['payment_mode'] = TaxationHistory.objects.values('payment_mode').annotate(total=Sum('amount'))

    return render(request, 'property/dashboard.html', context)


# load the data
def land_parcels(request):
    # fetch related data
    parcel_info = ParcelInfo.objects.select_related('parcel')
    parcelInfo = serialize('json', parcel_info)
    parcels = serialize('geojson', Parcels.objects.all())
    return HttpResponse(json.dumps([parcelInfo, parcels]))

class ParcelDetail():
    pass

@csrf_exempt
def ussd_callback(request):
    response = ""
    if request.method == "POST":
        session_id = request.POST.get("sessionId", None)
        service_code = request.POST.get("serviceCode", None)
        phone_number = request.POST.get("phoneNumber", None)
        text = request.POST.get("text", "default")

        if text == "":
            response += "CON Input Your Id Number"
        elif text == "0":
            response = "END"
        elif text != "":
            try:
                id_number = int(text)

                # get the land with the given Id
                parcels = ParcelInfo.objects.filter(id_number=id_number)

                if len(parcels) == 0:
                    response += "END No Land Registered with this " + str(id_number) + " number"
                else:
                    response += "END Land Rates Arrears for " + str(id_number) + ".\n"
                    for parcel in parcels:
                        print(parcel.parcel.plot_no)
                        response += "LR No. " + str(parcel.parcel.plot_no) + " has Ksh " + str(parcel.arrears) + " not paid.\n"
            except ValueError:
                response += "CON Invalid Input. Try Again"
        
        return HttpResponse(response)
            
# send bulk sms
import africastalking

username = "sandbox"
api_key = "a8e8c687b626df33676d5431121af6fd034f4812c88dec7113599399428f224a"
africastalking.initialize(username, api_key)

def send_message(request):
    parcels = ParcelInfo.objects.filter(arrears__gt=0).filter(~Q(phone_number=""))
    if request.method == "POST":
        # phone numbers
        recipients = ["+" + p.phone_number.strip() for p in parcels]

        # message
        date = datetime(2021, 2, 8)
        message = f"Kindly pay your arrears before or on {date.day}/{date.month}/{date.year}"

        # sender
        sender = '53820'

        # send that data
        try:
            response = africastalking.SMS.send(message, recipients, sender)
            print(response)
            return render(request, "property/unpaid_arrears.html", {'parcels':parcels})
        except Exception as e:
            print (f'Message error: {e}')
    else:
        recipients = ["+" + p.phone_number.strip() for p in parcels]
        print(recipients)
        
        return render(request, "property/unpaid_arrears.html", {'parcels':parcels})

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.forms.models import model_to_dict

from .forms import UserCreateForm, ProfileForm, UserDetailsForm
from .models import UserProfile, User

from property.models import ParcelInfo

class ProfileCreateView(LoginRequiredMixin, FormView):
    login_url = "/user/login/"
    model = UserProfile
    form_class = ProfileForm
    template_name = "user/create_profile.html"
    success_url = "/user/account/"     

    def get_initial(self):  
        user = User.objects.get(username = self.request.user.username)
        try:
            profile = UserProfile.objects.get(user=self.request.user)

            # get plot info 

            profile = {**model_to_dict(profile), **model_to_dict(user)}
        except UserProfile.DoesNotExist:
            profile = model_to_dict(user)
        
        return profile
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def form_valid(self, form):
        profile = form.save(commit=False)

        try:
            profile = UserProfile.objects.get(user=self.request.user)
            form = self.form_class(self.request.POST or None, self.request.FILES, instance=profile)
            form.save()
        except UserProfile.DoesNotExist:
            profile.user = self.request.user
            profile.image = self.request.FILES
            profile.save()

        print('Valid')
        user_details = self.request.user

        from operator import itemgetter
        first_name, last_name, surname = itemgetter('first_name', 'last_name', 'surname')(self.request.POST)

        user_details.first_name = first_name
        user_details.last_name = last_name
        user_details.surname = surname

        user_details.save()

        return redirect(self.success_url)
    
    def form_invalid(self, form):
        print(form)
        print(form.errors)
        return HttpResponse("Invalid data")


class UserCreateView(FormView):
    model = User
    template_name = "user/register.html"
    form_class= UserCreateForm
    success_url = "/user/login/"

    def form_valid(self, form):
        form.save()

        # update the user names from parcels db
        return redirect(self.success_url)


class ProfileView(LoginRequiredMixin, TemplateView):
    login_url = '/user/login/' 
    template_name = "user/user_profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["profile"] = UserProfile.objects.get(user = self.request.user)
            context['parcels'] = ParcelInfo.objects.filter(id_number = self.request.user.id_number)
        except UserProfile.DoesNotExist:
            context["profile"] = {}
        
        print(context['profile'])
        return context
    

property/templates/user/create_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}

{% block style %}
    <!-- <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"> -->
{% endblock %}

{% block content %}
<style>
  .navbar {
    width: 100%;
    box-shadow: 1px 1px 0.3em #343434;
  }
  .container {
      margin-top: 80px;
  }
  .spinner {
            position: absolute;
            top:0;
            left:0;
            right: 0;
            bottom: 0;
            z-index: 1;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #a3a3a36b;
        }

        .spinner div i {
            font-size: 2em;
            font-size: 2.5em;
            color: var(--primary);
            animation-name: spin;
            animation-duration: 2s;
            animation-timing-function: linear;
            animation-iteration-count: infinite;
        }

        @keyframes spin {
            from {
                transform:rotate(0deg);
            }
            to {
                transform: rotate(360deg);
            }
        }
</style>
{% include '../navbar.html' %}
<div class="spinner d-none">
  <div class="">
      <i class="fa fa-spinner"></i>
  </div>
</div>
<div class="container-fluid my-5 d-flex justify-content-center">
    <div class="col-md-6">
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_number">{{ form.first_name.label}}</label>
                    {{ form.first_name }}
                  </div>
        
                  <div class="form-group col-md-6">
                    <label for="phone_number">{{ form.phone_number.label }}</label>
                    {{ form.phone_number }}
                  </div>
              </div>
        
              <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="department">{{ form.last_name.label}}</label>
                    {{ form.last_name }}
                  </div>
        
                  <div class="form-group col-md-6">
                    <label for="employee_status">{{ form.surname.label }}</label>
                    {{ form.surname }}
                  </div>          
              </div>

              <div class="form-group">
                <label for="county">{{ form.email.label }}</label>
                {{ form.email }}
              </div>

              <div class="form-group">
                <label for="profile_pic">{{ form.image.label }}</label>
                {{ form.image }}
              </div>
              
              {% if form.email.value %}
                <input type="submit" name="Login" value="Update Profile" class="btn btn-brand mt-2">
              {% else %}
                <input type="submit" name="Login" value="Create Profile" class="btn btn-brand mt-2">
              {% endif %}
              
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/addControlClass.js' %}"></script>
<script>
  // spinner to indicate an action
  $('#payment_form').on("submit", function(e) {
      // load the spinner
      $('.spinner').toggleClass('d-none');
  });
</script>
{% endblock %}

property/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <style>
    .navbar {
      box-shadow: 1px 1px 0.5em var(--light-gray);
    }
    .custom-form {
      min-width: 30%;
      box-shadow: 1px 1px 0.5em var(--light-gray);
    }

    .custom-form p {
      margin: 0;
    }
  </style>
{% endblock %}

{% block content %}
{% include '../navbar.html' %}
<div class="container my-5 d-flex justify-content-center">
<div class="custom-form my-5">
  <form class="form-horizontal py-3 px-3" action="" method="post">
    <h5 class="text-center">Login</h5>
    {% csrf_token %}
      {{ form }}
      <input type="submit" name="Login" value="Login" class="btn btn-cta mt-2">
  </form>
  <p class="mx-2">Don't have an account? <a href="{% url 'user:register' %}"> Register.</a></p>
  <p class="mx-2">Forgot Password ?<a href="{% url 'user:login' %}"> Reset Password.</a></p>
</div>

</div>
{% endblock %}
{% block javascript %}
<script src="{% static 'js/addControlClass.js' %}"></script>
{% endblock %}

property/templates/user/logout.html
{% extends 'base.html' %}
{% block content %}
	<div class="container card col-md-6 offset-2 mt-5">
		<h6 class="">You have been logged out</h6>
		<div class="border-top pt-3">
			<small class="text-muted">
				<a href="{% url 'login' %}" class="ml-2">Log In Again</a>
			</small>
		</div>
	</div>
{% endblock %}

property/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <style>
    .container-fluid {
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .navbar {
      box-shadow: 1px 1px 0.5em var(--light-gray);
    }
    .custom-form {
      min-width: 30%;
      box-shadow: 1px 1px 0.5em var(--light-gray);
    }
  </style>
{% endblock %}

{% block content %}
{% include '../navbar.html' %}
<div class="container-fluid my-5">
  <div class="custom-form my-3">
    <form class="form-horizontal px-2 py-3" action="" method="post">
      <h5 class="text-center">Register</h5>
      {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            <label for="exampleInputEmail1">{{ field.label }}</label>
            {{ field }}
            <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
          </div>
        {% endfor %}
      
        <input type="submit" name="Register" value="Register" class="btn btn-cta">
    </form>
  <p class="mx-2">Already have an account ?<a href="{% url 'user:login' %}"> Login.</a></p>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/addControlClass.js' %}"></script>
{% endblock %}

property/templates/user/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <style>
        .navbar {
            width: 100%;
        }

        .container {
            margin-top: 80px;
        }
        .img-section {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .img-section .img-thumbnail {
            object-fit: cover;
            border-radius: 0px;
            height: auto;
            width: auto;
        }

        .section-info {
            margin: 1em 0px;
        }

        .section-info h5 {
            font-weight: 500;
            font-size: 1.1em;
            border-bottom: 1px solid var(--light-gray);
        }

        .account-info {
            margin: 0;
            display: flex;
            display: flex;
            justify-content: space-between;
        }

        .account-info b {
            font-weight: 500;
        }
        .messages {
            list-style: none;
        }

        .table th, .table td {
            padding: 0.3em;
            border-top:0px
        }        
    </style>
{% endblock %}

{% block content %}
{% include '../navbar.html' %}
    <div class="container">
        <!-- display payment messages -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="alert alert-{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="row py-4">
            <div class="col-md-4 img-section">
                <img src="{{ profile.image.url }}" alt="user" class="img-thumbnail">
                
                <h5>{{ profile.user.first_name|capfirst }}</h5>
                <a href="{% url 'user:create-profile' %}" class="btn btn-sm btn-cta mt-2">Update Profile </a>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-info">
                            <h5>Personal Information</h5>
                            <p class="account-info text-small"><b>Name</b> {{ profile.user.get_full_name }}</p>
                            <p class="account-info text-small"><b>Email</b> {{ profile.user.email }}</p>
                            <p class="account-info text-small"><b>Phone Number</b> {{ profile.phone_number }}</p>
                            <p class="account-info text-small"><b>Id Number</b> {{ profile.user.id_number }}</p>
                        </div>

                        <div class="section-info mt-5">
                            {% if user.is_taxpayer %}
                            <!-- plot information -->
                            <h5>Property Information</h5>
                            <table class="table">
                                <tr>
                                    <th>Plot Number</th>
                                    <th>Zone</th>
                                    <th>Arrears</th>
                                    <th>Payment Status</th>
                                </tr>

                                {% for parcel in parcels %}
                                    <tr>
                                       <td>{{ parcel.parcel.plot_no }}</td>
                                       <td>{{ parcel.parcel.zone }}</td>
                                       <td>{{ parcel.arrears }}</td>
                                       {% if parcel.arrears > 0 %}
                                            <td> 
                                                <a href="{% url 'mpesa:lipa-mpesa' parcel.parcel.plot_no parcel.arrears %}" 
                                                class="btn btn-sm btn-cta">Pay Your Arrears</a></td>
                                        {% else %}
                                            <td>
                                                <i class="fa fa-check-circle"></i>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </table>
                           {% endif %}
                        </div>
                    </div>
                      
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
<script src="{% static 'js/addControlClass.js' %}"></script>
<script>
    let url = window.location;
    if(location.search) {
        $('.spinner').toggleClass('d-none');

        setTimeout(function(e){
            $('.spinner').toggleClass('d-none');
            window.location.assign("/ user/account/");
        }, 3000);
    }
</script>
{% endblock %}