property/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import map_view, dashboard_view, land_parcels, landing_page, graph_data, ussd_callback, send_message

app_name = "property"

urlpatterns = [
    path("", landing_page, name="landing"),
    path("map/", map_view, name="map"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("parcels/", land_parcels, name="land-parcels"),
    path("graph_data/", graph_data, name="graph-data"),
    path("ussd_callback/",ussd_callback, name="ussd-callback"),
    path("send_message/", send_message, name="send-message")
]

# configure static anf media files
if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property_taxation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
    path("api/", include("mpesa.urls")),
    path("", include("property.urls")),
   
]

user/urls.py
from django.urls import path

# authentication
from django.contrib.auth.views import LoginView, LogoutView
from .views import ProfileView, UserCreateView, ProfileCreateView


# application namspace
app_name = "user"

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="user/login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="user/logout.html"), name="logout"),

    path("create_profile/", ProfileCreateView.as_view(), name="create-profile"),
    path("account/", ProfileView.as_view(), name="profile")
]   

property/models.py
from django.contrib.gis.db import models

class Parcels(models.Model):
    id = models.BigIntegerField()
    geom = models.MultiPolygonField(srid=3857, blank=True, null=True)
    plot_no = models.BigIntegerField(primary_key=True)
    owner = models.CharField(max_length=50, blank=True, null=True),
    zone = models.CharField("Parcel Zone", max_length=50, default="Zone A")

    class Meta:
        managed = False
        db_table = 'parcels'

class TaxationHistory(models.Model):
    PAYMENT_MODE = (
        ('MPESA', "M-PESA"),
        ('Bank', "Bank")
    )

    # parcel = models.ForeignKey(Parcels, db_column='plot_no', on_delete=models.CASCADE)
    plot_no = models.BigIntegerField(blank=True, null=True)
    payed_on = models.DateTimeField("Payed On", auto_now=False, auto_now_add=False)
    is_waived = models.BooleanField("Waiver", default=False)
    payment_mode = models.CharField("Payment Method", max_length=50, choices=PAYMENT_MODE)
    amount = models.IntegerField("Amount", blank=True, null=True)
    balance = models.IntegerField("Arrear", default=0)
    transaction_id = models.CharField("Transaction Id", max_length=50)
    id_number = models.IntegerField("Id Number")

    class Meta:
        verbose_name = "Tax History"
        verbose_name_plural = "Tax History"

    def __str__(self):
        return self.transaction_id

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

class ParcelInfo(models.Model):
    id = models.IntegerField(primary_key=True)
    parcel = models.OneToOneField(Parcels, db_column='plot_no', blank=True, null=True, on_delete=models.CASCADE)
    owner = models.CharField(max_length=255, blank=True, null=True)
    arrears = models.CharField(max_length=100, blank=True, null=True)
    is_cleared = models.BooleanField("Arrears Cleared", default=False)
    id_number = models.BigIntegerField("Owner Id Number", unique=False)
    phone_number = models.CharField("Phone Number", max_length=15, blank=True)

    class Meta:
        managed = False
        db_table = 'parcel_info'

property/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum, Q
from django.views.decorators.csrf import csrf_exempt

# serializer
from django.core.serializers import serialize

# models
from .models import ParcelInfo, Parcels, TaxationHistory

# utils
import json
import requests
from datetime import datetime

def landing_page(request):
    if request.GET.get('plot_no'):
        plot_no = request.GET.get('plot_no')
        try:
            parcel = ParcelInfo.objects.get(parcel = plot_no)
            parcel = {'arrears':parcel.arrears, 'parcel':parcel.parcel}
        except ParcelInfo.DoesNotExist:
            parcel = "None"
        
        context = {'parcel':parcel}
    else:
        context =  {}
        
    return render(request, 'property/landing.html', context)

def graph_data(request):
    arrears_zone = ParcelInfo.objects.values('parcel__zone').annotate(total=Sum('arrears'))
    collection_history = TaxationHistory.objects.values('payed_on__year').annotate(total=Sum('amount'))
    payment_mode = TaxationHistory.objects.values('payment_mode').annotate(total=Sum('amount'))

    arrears_zone = [{ar['parcel__zone']:ar['total']} for ar in arrears_zone]
    collection_history = [{ar['payed_on__year']:ar['total']} for ar in collection_history]
    payment_mode = [{ar['payment_mode']:ar['total']} for ar in payment_mode ]

    return JsonResponse({'arrear':arrears_zone, 'collection':collection_history, 'payment_mode':payment_mode})

    # 
# Create your views here.
def map_view(request):
    return render(request, 'property/map.html')

def dashboard_view(request):
    context = {}
    context['parcels_count'] = Parcels.objects.all().count()
    context['owner_count'] = ParcelInfo.objects.values('id_number').annotate(Count('id_number', distinct=True)).count()
    context['arrears'] = ParcelInfo.objects.aggregate(total = Sum('arrears'))

    # collected this year
    currentTime = datetime.now()
    year = currentTime.year
    dt = datetime(year, 1, 1)
    context['collected'] = TaxationHistory.objects.filter(payed_on__gte = dt).aggregate(total=Sum('amount'))
    context['arrears_zone'] = ParcelInfo.objects.values('parcel__zone').annotate(total=Sum('arrears'))
    context['collection_history'] = TaxationHistory.objects.values('payed_on__year').annotate(total=Sum('amount'))
    context['payment_mode'] = TaxationHistory.objects.values('payment_mode').annotate(total=Sum('amount'))

    return render(request, 'property/dashboard.html', context)


# load the data
def land_parcels(request):
    # fetch related data
    parcel_info = ParcelInfo.objects.select_related('parcel')
    parcelInfo = serialize('json', parcel_info)
    parcels = serialize('geojson', Parcels.objects.all())
    return HttpResponse(json.dumps([parcelInfo, parcels]))

class ParcelDetail():
    pass

@csrf_exempt
def ussd_callback(request):
    response = ""
    if request.method == "POST":
        session_id = request.POST.get("sessionId", None)
        service_code = request.POST.get("serviceCode", None)
        phone_number = request.POST.get("phoneNumber", None)
        text = request.POST.get("text", "default")

        if text == "":
            response += "CON Input Your Id Number"
        elif text == "0":
            response = "END"
        elif text != "":
            try:
                id_number = int(text)

                # get the land with the given Id
                parcels = ParcelInfo.objects.filter(id_number=id_number)

                if len(parcels) == 0:
                    response += "END No Land Registered with this " + str(id_number) + " number"
                else:
                    response += "END Land Rates Arrears for " + str(id_number) + ".\n"
                    for parcel in parcels:
                        print(parcel.parcel.plot_no)
                        response += "LR No. " + str(parcel.parcel.plot_no) + " has Ksh " + str(parcel.arrears) + " not paid.\n"
            except ValueError:
                response += "CON Invalid Input. Try Again"
        
        return HttpResponse(response)
            
# send bulk sms
import africastalking

username = "sandbox"
api_key = "a8e8c687b626df33676d5431121af6fd034f4812c88dec7113599399428f224a"
africastalking.initialize(username, api_key)

def send_message(request):
    parcels = ParcelInfo.objects.filter(arrears__gt=0).filter(~Q(phone_number=""))
    if request.method == "POST":
        # phone numbers
        recipients = ["+" + p.phone_number.strip() for p in parcels]

        # message
        date = datetime(2021, 2, 8)
        message = f"Kindly pay your arrears before or on {date.day}/{date.month}/{date.year}"

        # sender
        sender = '53820'

        # send that data
        try:
            response = africastalking.SMS.send(message, recipients, sender)
            print(response)
            return render(request, "property/unpaid_arrears.html", {'parcels':parcels})
        except Exception as e:
            print (f'Message error: {e}')
    else:
        recipients = ["+" + p.phone_number.strip() for p in parcels]
        print(recipients)
        
        return render(request, "property/unpaid_arrears.html", {'parcels':parcels})

property/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>

    <!-- dependencies css -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    {% block style %}
    {% endblock %}
</head>
<body>
      <!-- content -->
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <script src="{% static '/js/jquery.js' %}"></script>
    <script src="{% static '/bootstrap/js/bootstrap.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

property/templates/nav.html
<div class="container-fluid navbar">
    <div class="row">
        <div class="col-xs-12 col-sm-2">
            <a class="navbar-brand bg-brand" href="{% url 'property:landing' %}">Property Taxation</a>
        </div>
        
        <div class="col-xs-12 col-sm-10">
        </div>
    </div>
</div>

property/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'property:landing' %}">Property Taxation</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav my-2 my-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'property:landing' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated and user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'property:map' %}">Map</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'property:dashboard' %}">Dashboard</a>
        </li>
        {% endif %}
      </ul>

      <ul class="navbar-nav">            
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
          </li>

          {% if user.is_taxpayer %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:profile' %}">Account</a>
            </li>
          {% endif %}
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

property/templates/sidenav.html
<div class="side-section bg-brand">
    <ul class="list-item">
        <li>
            <a href="{% url 'property:landing' %}">
                <i class="fa fa-home"></i>
                <span>Home</span>
            </a>
        </li>
        <li>
            <a href="{% url 'property:dashboard' %}">
                <i class="fa fa-area-chart"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a href="{% url 'property:map' %}">
                <i class="fa fa-map"></i>
                <span>Map</span>
            </a>
        </li>

        <li>
            <a href="{% url 'user:profile' %}">
                <i class="fa fa-user"></i>
                <span>Account</span>
            </a>
        </li>

    </ul>
    <!-- <img src="/media/buffer.PNG" alt="" class="img-circle img-responsive"> -->
</div>